### ISSUE TITLE
"Forgot password" link is not working

### ISSUE THREAD

**Issue by ClaudenirFreitas** [curityio/username-password-authenticator#9]
Hi Curity,

I am creating a new authenticator internally using this one as an example and I saw that the "Forgot password" link is not working as expected.

I am creating this issue because I believe it might be useful for other developers.

Can you help me to understand how to implement this page?

Thanks in advance.

Some evidences bellow:

Authenticator page:
![Screenshot 2022-02-11 at 12 57 49](https://user-images.githubusercontent.com/7038458/153595539-7c822293-ec1e-4a9b-98d3-d621df5243b4.png)

Not found Forgot Password page
![Screenshot 2022-02-11 at 12 57 37](https://user-images.githubusercontent.com/7038458/153595532-02772346-d03f-42ca-8de0-d86a92e30bcd.png)

**Comment by mtrojanowski** [comment]
Hey @ClaudenirFreitas,

These two functions (reset password and remind username), unfortunately, are not implemented in this example authenticator. I have removed the links from the default template. It would be quite tricky to implement this using the SDK so I would rather recommend using the built-in authenticator together with actions if you need to add some custom behaviour to the authentication. You can also create an authentication action plugin and make sure it runs after the username-password authenticator.
